/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MetaLQGfactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "LQG" | "createMetaLQG" | "isMetaLQG"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "CreateMetaLQG"): EventFragment;

  encodeFunctionData(functionFragment: "LQG", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createMetaLQG",
    values: [AddressLike, BigNumberish, AddressLike, string, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isMetaLQG",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "LQG", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createMetaLQG",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isMetaLQG",
    data: BytesLike
  ): Result;
}

export namespace CreateMetaLQGEvent {
  export type InputTuple = [
    metaLQG: AddressLike,
    caller: AddressLike,
    initialOwner: AddressLike,
    initialTimelock: BigNumberish,
    asset: AddressLike,
    name: string,
    symbol: string,
    salt: BytesLike
  ];
  export type OutputTuple = [
    metaLQG: string,
    caller: string,
    initialOwner: string,
    initialTimelock: bigint,
    asset: string,
    name: string,
    symbol: string,
    salt: string
  ];
  export interface OutputObject {
    metaLQG: string;
    caller: string;
    initialOwner: string;
    initialTimelock: bigint;
    asset: string;
    name: string;
    symbol: string;
    salt: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MetaLQGfactory extends BaseContract {
  connect(runner?: ContractRunner | null): MetaLQGfactory;
  waitForDeployment(): Promise<this>;

  interface: MetaLQGfactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LQG: TypedContractMethod<[], [string], "view">;

  createMetaLQG: TypedContractMethod<
    [
      initialOwner: AddressLike,
      initialTimelock: BigNumberish,
      asset: AddressLike,
      name: string,
      symbol: string,
      salt: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  isMetaLQG: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LQG"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createMetaLQG"
  ): TypedContractMethod<
    [
      initialOwner: AddressLike,
      initialTimelock: BigNumberish,
      asset: AddressLike,
      name: string,
      symbol: string,
      salt: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isMetaLQG"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getEvent(
    key: "CreateMetaLQG"
  ): TypedContractEvent<
    CreateMetaLQGEvent.InputTuple,
    CreateMetaLQGEvent.OutputTuple,
    CreateMetaLQGEvent.OutputObject
  >;

  filters: {
    "CreateMetaLQG(address,address,address,uint256,address,string,string,bytes32)": TypedContractEvent<
      CreateMetaLQGEvent.InputTuple,
      CreateMetaLQGEvent.OutputTuple,
      CreateMetaLQGEvent.OutputObject
    >;
    CreateMetaLQG: TypedContractEvent<
      CreateMetaLQGEvent.InputTuple,
      CreateMetaLQGEvent.OutputTuple,
      CreateMetaLQGEvent.OutputObject
    >;
  };
}
